### PR TITLE
Fixing ct test related ctp 766

### PR DESCRIPTION
**Pull request by acbeni**
@lauraluiz this PR is intended to make the CI tests run once again.

### CODE REVIEW

**Comment by acbeni** [comment]
@lauraluiz the tests have been changed in order to be more consistent as agreed,
how does it seem to you?

**Comment by lauraluiz** [comment]
Some search endpoint tests are failing, are they the flaky ones?

**Comment by acbeni** [comment]
thx @lauraluiz ☺️

**Comment by acbeni** [comment]
@lauraluiz Yep they are related to search as always 😢

**Pull request merged**
