### PR TITLE
Order by order number

### LINKED ISSUE #1562: Get/Update/Delete order by order number
We should add support for getting, updating and deleting of an `Order` by it's order number. And we should take the chance to review our code generator, may be it makes sense to make it more generic with regards to the property that it uses in the generated code (currently we only support the more common `id` and `key`).

### PR DESCRIPTION
**Pull request by katmatt**
Closes #1562

### CODE REVIEW

**Comment by acbeni** [comment]
But these tests fail even locally
`OrderDeleteCommandIntegrationTest`
`OrderUpdateCommandIntegrationTest`
`OrderQueryIntegrationTest`

**Comment by katmatt** [comment]
@acbeni At least one test was successful 😉 Would be great if you take another look at my most recent changes 😄

**Comment by acbeni** [comment]
@katmatt yep i saw it yesterday, i just restated the test that fails just to make sure it's just a temporary failure 😄

**Comment by acbeni** [comment]
you are good to merge 👍

**Pull request merged**
