### PR TITLE
#1989 add new oauth scopes

### LINKED ISSUE #1989: add-new-oauth-scopes

### PR DESCRIPTION
**Pull request by alex-ct**
# Description

Closes #1989 

# Checklist

- [x] Update release Notes
- [ ] Add to the current github milestone 
- [ ] Update commercetools api reference

### CODE REVIEW

**Comment by alex-ct** [comment]
> Looks very good to me 👍
> The only addition i have is to mark old scopes with @deprecated annotation, with depration reason being replaced by new scopes.

are those scopes deprecated only for certain endpoints or for all endpoints ?

**Comment by acbeni** [comment]
they are deprecated for all, according to doc.

**Comment by alex-ct** [comment]
> they are deprecated for all, according to doc.

ok then :)

**Comment by acbeni** [comment]
Sorry alex, just checked the doc again, you are right these changes are limited to discount code, which means no need to add the @deprecated annotation.

**Comment by katmatt** [comment]
@acbeni You still need `manage_orders:{projectKey}` and `view_orders:{projectKey}` for working with orders. They are only deprecated for the listed endpoints. Otherwise Christoph would have them marked as deprecated on the orders endpoints file too 😉

**Pull request merged**
